name = "SQLStore"
uuid = "fadf0b4e-86bc-4bbb-a4ee-5c756d629598"
authors = ["Alexander Plavin <alexander@plav.in>"]
version = "0.1.10"

[deps]
DBInterface = "a10d1c49-ce27-4219-8d33-6db1a4562965"
DataAPI = "9a962f9c-6df0-11e9-0e5d-c546b8b5ee8a"
DataPipes = "02685ad9-2d12-40c3-9f73-c6aeda6a7ff5"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
InvertedIndices = "41ab1584-1d38-5bbf-9106-f11c6c58b48f"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
DBInterface = "2.5.0"
DataAPI = "1.9.0"
DataPipes = "0.1.12"
InvertedIndices = "1.1.0"
JSON3 = "1.9.2"
SQLite = "1.3.0"
Tables = "1.6.0"
julia = "1.6"
